//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class CategoryXProductXStoreLocale
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    if (Category != null && Category.Id != value)
                    {
                        Category = null;
                    }
                    _categoryId = value;
                }
            }
        }
        private System.Guid _categoryId;
    
        public virtual System.Guid ProductXStoreLocaleId
        {
            get { return _productXStoreLocaleId; }
            set
            {
                if (_productXStoreLocaleId != value)
                {
                    if (ProductXStoreLocale != null && ProductXStoreLocale.Id != value)
                    {
                        ProductXStoreLocale = null;
                    }
                    _productXStoreLocaleId = value;
                }
            }
        }
        private System.Guid _productXStoreLocaleId;
    
        public virtual string RouteUrl
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Category Category
        {
            get { return _category; }
            set
            {
                if (!ReferenceEquals(_category, value))
                {
                    var previousValue = _category;
                    _category = value;
                    FixupCategory(previousValue);
                }
            }
        }
        private Category _category;
    
        public virtual ProductXStoreLocale ProductXStoreLocale
        {
            get { return _productXStoreLocale; }
            set
            {
                if (!ReferenceEquals(_productXStoreLocale, value))
                {
                    var previousValue = _productXStoreLocale;
                    _productXStoreLocale = value;
                    FixupProductXStoreLocale(previousValue);
                }
            }
        }
        private ProductXStoreLocale _productXStoreLocale;

        #endregion

        #region Association Fixup
    
        private void FixupCategory(Category previousValue)
        {
            if (previousValue != null && previousValue.CategoryXProductXStoreLocale.Contains(this))
            {
                previousValue.CategoryXProductXStoreLocale.Remove(this);
            }
    
            if (Category != null)
            {
                if (!Category.CategoryXProductXStoreLocale.Contains(this))
                {
                    Category.CategoryXProductXStoreLocale.Add(this);
                }
                if (CategoryId != Category.Id)
                {
                    CategoryId = Category.Id;
                }
            }
        }
    
        private void FixupProductXStoreLocale(ProductXStoreLocale previousValue)
        {
            if (previousValue != null && previousValue.CategoryXProductXStoreLocale.Contains(this))
            {
                previousValue.CategoryXProductXStoreLocale.Remove(this);
            }
    
            if (ProductXStoreLocale != null)
            {
                if (!ProductXStoreLocale.CategoryXProductXStoreLocale.Contains(this))
                {
                    ProductXStoreLocale.CategoryXProductXStoreLocale.Add(this);
                }
                if (ProductXStoreLocaleId != ProductXStoreLocale.Id)
                {
                    ProductXStoreLocaleId = ProductXStoreLocale.Id;
                }
            }
        }

        #endregion

    }
}
