//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class CategoryXProductXTenantLocale
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    if (Category != null && Category.Id != value)
                    {
                        Category = null;
                    }
                    _categoryId = value;
                }
            }
        }
        private System.Guid _categoryId;
    
        public virtual System.Guid ProductXTenantLocaleId
        {
            get { return _productXTenantLocaleId; }
            set
            {
                if (_productXTenantLocaleId != value)
                {
                    if (ProductXTenantLocale != null && ProductXTenantLocale.Id != value)
                    {
                        ProductXTenantLocale = null;
                    }
                    _productXTenantLocaleId = value;
                }
            }
        }
        private System.Guid _productXTenantLocaleId;
    
        public virtual string RouteUrl
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ProductXTenantLocale ProductXTenantLocale
        {
            get { return _productXTenantLocale; }
            set
            {
                if (!ReferenceEquals(_productXTenantLocale, value))
                {
                    var previousValue = _productXTenantLocale;
                    _productXTenantLocale = value;
                    FixupProductXTenantLocale(previousValue);
                }
            }
        }
        private ProductXTenantLocale _productXTenantLocale;
    
        public virtual Category Category
        {
            get { return _category; }
            set
            {
                if (!ReferenceEquals(_category, value))
                {
                    var previousValue = _category;
                    _category = value;
                    FixupCategory(previousValue);
                }
            }
        }
        private Category _category;

        #endregion

        #region Association Fixup
    
        private void FixupProductXTenantLocale(ProductXTenantLocale previousValue)
        {
            if (previousValue != null && previousValue.CategoryXProductXTenantLocale.Contains(this))
            {
                previousValue.CategoryXProductXTenantLocale.Remove(this);
            }
    
            if (ProductXTenantLocale != null)
            {
                if (!ProductXTenantLocale.CategoryXProductXTenantLocale.Contains(this))
                {
                    ProductXTenantLocale.CategoryXProductXTenantLocale.Add(this);
                }
                if (ProductXTenantLocaleId != ProductXTenantLocale.Id)
                {
                    ProductXTenantLocaleId = ProductXTenantLocale.Id;
                }
            }
        }
    
        private void FixupCategory(Category previousValue)
        {
            if (previousValue != null && previousValue.CategoryXProductXTenantLocale.Contains(this))
            {
                previousValue.CategoryXProductXTenantLocale.Remove(this);
            }
    
            if (Category != null)
            {
                if (!Category.CategoryXProductXTenantLocale.Contains(this))
                {
                    Category.CategoryXProductXTenantLocale.Add(this);
                }
                if (CategoryId != Category.Id)
                {
                    CategoryId = Category.Id;
                }
            }
        }

        #endregion

    }
}
