//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexCommerce.Data.SqlServer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplexCommerce : DbContext
    {
        public ComplexCommerce()
            : base("name=ComplexCommerce")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryXProduct> CategoryXProducts { get; set; }
        public DbSet<Chain> Chains { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductXStoreXLocale> ProductXStoreXLocales { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreLocale> StoreLocale { get; set; }
    }
}
