//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System.Data;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Common;
using ComplexCommerce.Data.SqlServer.Model.ComplexCommerceMockObjectSet;

namespace ComplexCommerce.Data.SqlServer.Model
{
    /// <summary>
    /// The concrete mock context object that implements the context's interface.
    /// Provide an instance of this mock context class to client logic when testing, 
    /// instead of providing a functional context object.
    /// </summary>
    public partial class ComplexCommerceMock : ObjectContextMockBase, IComplexCommerce
    {
    	public ComplexCommerceMock(IObjectContext objectContext)
            : base(objectContext)
        {
        }
        public virtual IObjectSet<Chain> Chain
        {
            get { return _chain  ?? (_chain = new MockObjectSet<Chain>()); }
        }
        private IObjectSet<Chain> _chain;
        public virtual IObjectSet<Product> Product
        {
            get { return _product  ?? (_product = new MockObjectSet<Product>()); }
        }
        private IObjectSet<Product> _product;
        public virtual IObjectSet<CategoryXProductXTenantLocale> CategoryXProductXTenantLocale
        {
            get { return _categoryXProductXTenantLocale  ?? (_categoryXProductXTenantLocale = new MockObjectSet<CategoryXProductXTenantLocale>()); }
        }
        private IObjectSet<CategoryXProductXTenantLocale> _categoryXProductXTenantLocale;
        public virtual IObjectSet<ProductXTenantLocale> ProductXTenantLocale
        {
            get { return _productXTenantLocale  ?? (_productXTenantLocale = new MockObjectSet<ProductXTenantLocale>()); }
        }
        private IObjectSet<ProductXTenantLocale> _productXTenantLocale;
        public virtual IObjectSet<Tenant> Tenant
        {
            get { return _tenant  ?? (_tenant = new MockObjectSet<Tenant>()); }
        }
        private IObjectSet<Tenant> _tenant;
        public virtual IObjectSet<TenantLocale> TenantLocale
        {
            get { return _tenantLocale  ?? (_tenantLocale = new MockObjectSet<TenantLocale>()); }
        }
        private IObjectSet<TenantLocale> _tenantLocale;
        public virtual IObjectSet<Category> Category
        {
            get { return _category  ?? (_category = new MockObjectSet<Category>()); }
        }
        private IObjectSet<Category> _category;
        public virtual IObjectSet<Page> Page
        {
            get { return _page  ?? (_page = new MockObjectSet<Page>()); }
        }
        private IObjectSet<Page> _page;
    }
}
