//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Data;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;

namespace ComplexCommerce.Data.SqlServer.Model
{
    /// <summary>
    /// The interface for the specialized object context. This contains all of
    /// the <code>IDbSet</code> properties that are implemented in both the
    /// functional context class and the mock context class.
    /// </summary>
    public interface IComplexCommerce : IDbContext
    {
        IDbSet<Chain> Chain { get; set; }
        IDbSet<Product> Product { get; set; }
        IDbSet<CategoryXProductXTenantLocale> CategoryXProductXTenantLocale { get; set; }
        IDbSet<TenantLocale> TenantLocale { get; set; }
        IDbSet<Tenant> Tenant { get; set; }
        IDbSet<Page> Page { get; set; }
        IDbSet<ProductXTenantLocale> ProductXTenantLocale { get; set; }
    }
}
