//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class Page
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> ParentId
        {
            get;
            set;
        }
    
        public virtual System.Guid StoreLocaleId
        {
            get { return _storeLocaleId; }
            set
            {
                if (_storeLocaleId != value)
                {
                    if (StoreLocale != null && StoreLocale.Id != value)
                    {
                        StoreLocale = null;
                    }
                    _storeLocaleId = value;
                }
            }
        }
        private System.Guid _storeLocaleId;
    
        public virtual string RouteUrl
        {
            get;
            set;
        }
    
        public virtual int ContentTypeId
        {
            get;
            set;
        }
    
        public virtual System.Guid ContentId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual StoreLocale StoreLocale
        {
            get { return _storeLocale; }
            set
            {
                if (!ReferenceEquals(_storeLocale, value))
                {
                    var previousValue = _storeLocale;
                    _storeLocale = value;
                    FixupStoreLocale(previousValue);
                }
            }
        }
        private StoreLocale _storeLocale;

        #endregion

        #region Association Fixup
    
        private void FixupStoreLocale(StoreLocale previousValue)
        {
            if (previousValue != null && previousValue.Page.Contains(this))
            {
                previousValue.Page.Remove(this);
            }
    
            if (StoreLocale != null)
            {
                if (!StoreLocale.Page.Contains(this))
                {
                    StoreLocale.Page.Add(this);
                }
                if (StoreLocaleId != StoreLocale.Id)
                {
                    StoreLocaleId = StoreLocale.Id;
                }
            }
        }

        #endregion

    }
}
