//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexCommerce.Data.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid TenantLocaleId { get; set; }
        public int ContentType { get; set; }
        public System.Guid ContentId { get; set; }
        public string RouteUrl { get; set; }
        public string Title { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaRobots { get; set; }
        public bool IsVisibleOnMainMenu { get; set; }
    
        public virtual TenantLocale TenantLocale { get; set; }
    }
}
