//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class ProductXTenantLocale
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    if (Product != null && Product.Id != value)
                    {
                        Product = null;
                    }
                    _productId = value;
                }
            }
        }
        private System.Guid _productId;
    
        public virtual System.Guid TenantLocaleId
        {
            get { return _tenantLocaleId; }
            set
            {
                if (_tenantLocaleId != value)
                {
                    if (TenantLocale != null && TenantLocale.Id != value)
                    {
                        TenantLocale = null;
                    }
                    _tenantLocaleId = value;
                }
            }
        }
        private System.Guid _tenantLocaleId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string UrlSlug
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CategoryXProductXTenantLocale> CategoryXProductXTenantLocale
        {
            get
            {
                if (_categoryXProductXTenantLocale == null)
                {
                    var newCollection = new FixupCollection<CategoryXProductXTenantLocale>();
                    newCollection.CollectionChanged += FixupCategoryXProductXTenantLocale;
                    _categoryXProductXTenantLocale = newCollection;
                }
                return _categoryXProductXTenantLocale;
            }
            set
            {
                if (!ReferenceEquals(_categoryXProductXTenantLocale, value))
                {
                    var previousValue = _categoryXProductXTenantLocale as FixupCollection<CategoryXProductXTenantLocale>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCategoryXProductXTenantLocale;
                    }
                    _categoryXProductXTenantLocale = value;
                    var newValue = value as FixupCollection<CategoryXProductXTenantLocale>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCategoryXProductXTenantLocale;
                    }
                }
            }
        }
        private ICollection<CategoryXProductXTenantLocale> _categoryXProductXTenantLocale;
    
        public virtual Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                }
            }
        }
        private Product _product;
    
        public virtual TenantLocale TenantLocale
        {
            get { return _tenantLocale; }
            set
            {
                if (!ReferenceEquals(_tenantLocale, value))
                {
                    var previousValue = _tenantLocale;
                    _tenantLocale = value;
                    FixupTenantLocale(previousValue);
                }
            }
        }
        private TenantLocale _tenantLocale;

        #endregion

        #region Association Fixup
    
        private void FixupProduct(Product previousValue)
        {
            if (previousValue != null && previousValue.ProductXTenantLocale.Contains(this))
            {
                previousValue.ProductXTenantLocale.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.ProductXTenantLocale.Contains(this))
                {
                    Product.ProductXTenantLocale.Add(this);
                }
                if (ProductId != Product.Id)
                {
                    ProductId = Product.Id;
                }
            }
        }
    
        private void FixupTenantLocale(TenantLocale previousValue)
        {
            if (previousValue != null && previousValue.ProductXTenantLocale.Contains(this))
            {
                previousValue.ProductXTenantLocale.Remove(this);
            }
    
            if (TenantLocale != null)
            {
                if (!TenantLocale.ProductXTenantLocale.Contains(this))
                {
                    TenantLocale.ProductXTenantLocale.Add(this);
                }
                if (TenantLocaleId != TenantLocale.Id)
                {
                    TenantLocaleId = TenantLocale.Id;
                }
            }
        }
    
        private void FixupCategoryXProductXTenantLocale(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CategoryXProductXTenantLocale item in e.NewItems)
                {
                    item.ProductXTenantLocale = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CategoryXProductXTenantLocale item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductXTenantLocale, this))
                    {
                        item.ProductXTenantLocale = null;
                    }
                }
            }
        }

        #endregion

    }
}
