//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexCommerce.Data.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductXTenantLocale
    {
        public ProductXTenantLocale()
        {
            this.CategoryXProductXTenantLocale = new HashSet<CategoryXProductXTenantLocale>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid TenantLocaleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UrlSlug { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public System.Guid DefaultCategoryId { get; set; }
    
        public virtual ICollection<CategoryXProductXTenantLocale> CategoryXProductXTenantLocale { get; set; }
        public virtual Product Product { get; set; }
        public virtual TenantLocale TenantLocale { get; set; }
    }
}
