//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class Store
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int ChainId
        {
            get { return _chainId; }
            set
            {
                if (_chainId != value)
                {
                    if (Chain != null && Chain.Id != value)
                    {
                        Chain = null;
                    }
                    _chainId = value;
                }
            }
        }
        private int _chainId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string LogoUrl
        {
            get;
            set;
        }
    
        public virtual string Domain
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DefaultLocaleId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Chain Chain
        {
            get { return _chain; }
            set
            {
                if (!ReferenceEquals(_chain, value))
                {
                    var previousValue = _chain;
                    _chain = value;
                    FixupChain(previousValue);
                }
            }
        }
        private Chain _chain;
    
        public virtual ICollection<StoreLocale> StoreLocale
        {
            get
            {
                if (_storeLocale == null)
                {
                    var newCollection = new FixupCollection<StoreLocale>();
                    newCollection.CollectionChanged += FixupStoreLocale;
                    _storeLocale = newCollection;
                }
                return _storeLocale;
            }
            set
            {
                if (!ReferenceEquals(_storeLocale, value))
                {
                    var previousValue = _storeLocale as FixupCollection<StoreLocale>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStoreLocale;
                    }
                    _storeLocale = value;
                    var newValue = value as FixupCollection<StoreLocale>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStoreLocale;
                    }
                }
            }
        }
        private ICollection<StoreLocale> _storeLocale;

        #endregion

        #region Association Fixup
    
        private void FixupChain(Chain previousValue)
        {
            if (previousValue != null && previousValue.Store.Contains(this))
            {
                previousValue.Store.Remove(this);
            }
    
            if (Chain != null)
            {
                if (!Chain.Store.Contains(this))
                {
                    Chain.Store.Add(this);
                }
                if (ChainId != Chain.Id)
                {
                    ChainId = Chain.Id;
                }
            }
        }
    
        private void FixupStoreLocale(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StoreLocale item in e.NewItems)
                {
                    item.Store = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StoreLocale item in e.OldItems)
                {
                    if (ReferenceEquals(item.Store, this))
                    {
                        item.Store = null;
                    }
                }
            }
        }

        #endregion

    }
}
