//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexCommerce.Data.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.StoreLocale = new HashSet<StoreLocale>();
        }
    
        public System.Guid Id { get; set; }
        public int ChainId { get; set; }
        public string Name { get; set; }
        public string LogoUrl { get; set; }
        public string Domain { get; set; }
        public Nullable<int> DefaultLocaleId { get; set; }
    
        public virtual Chain Chain { get; set; }
        public virtual ICollection<StoreLocale> StoreLocale { get; set; }
    }
}
