//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ComplexCommerce.Data.SqlServer.Model
{
    public partial class Tenant
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int ChainId
        {
            get { return _chainId; }
            set
            {
                if (_chainId != value)
                {
                    if (Chain != null && Chain.Id != value)
                    {
                        Chain = null;
                    }
                    _chainId = value;
                }
            }
        }
        private int _chainId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string LogoUrl
        {
            get;
            set;
        }
    
        public virtual string Host
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DefaultLocaleId
        {
            get;
            set;
        }
    
        public virtual int TenantType
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Chain Chain
        {
            get { return _chain; }
            set
            {
                if (!ReferenceEquals(_chain, value))
                {
                    var previousValue = _chain;
                    _chain = value;
                    FixupChain(previousValue);
                }
            }
        }
        private Chain _chain;
    
        public virtual ICollection<TenantLocale> TenantLocale
        {
            get
            {
                if (_tenantLocale == null)
                {
                    var newCollection = new FixupCollection<TenantLocale>();
                    newCollection.CollectionChanged += FixupTenantLocale;
                    _tenantLocale = newCollection;
                }
                return _tenantLocale;
            }
            set
            {
                if (!ReferenceEquals(_tenantLocale, value))
                {
                    var previousValue = _tenantLocale as FixupCollection<TenantLocale>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTenantLocale;
                    }
                    _tenantLocale = value;
                    var newValue = value as FixupCollection<TenantLocale>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTenantLocale;
                    }
                }
            }
        }
        private ICollection<TenantLocale> _tenantLocale;

        #endregion

        #region Association Fixup
    
        private void FixupChain(Chain previousValue)
        {
            if (previousValue != null && previousValue.Tenant.Contains(this))
            {
                previousValue.Tenant.Remove(this);
            }
    
            if (Chain != null)
            {
                if (!Chain.Tenant.Contains(this))
                {
                    Chain.Tenant.Add(this);
                }
                if (ChainId != Chain.Id)
                {
                    ChainId = Chain.Id;
                }
            }
        }
    
        private void FixupTenantLocale(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TenantLocale item in e.NewItems)
                {
                    item.Tenant = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TenantLocale item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tenant, this))
                    {
                        item.Tenant = null;
                    }
                }
            }
        }

        #endregion

    }
}
